"""Add User model

Revision ID: bceb2c538b90
Revises: 7c622399b283
Create Date: 2023-12-12 20:33:59.877343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bceb2c538b90'
down_revision = '7c622399b283'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
